
export const env = {
  API_URL: String(import.meta.env.VITE_API_URL),
  CLOUDINARY_CLOUD_NAME: String(import.meta.env.VITE_CLOUDINARY_CLOUD_NAME),
  CLOUDINARY_API_KEY: String(import.meta.env.VITE_CLOUDINARY_API_KEY),
  CLOUDINARY_API_SECRET: String(import.meta.env.VITE_CLOUDINARY_API_SECRET),
  CLOUDINARY_UPLOAD_PRESET: String(import.meta.env.VITE_CLOUDINARY_UPLOAD_PRESET),
  TWITTER_CLIENT_ID: String(import.meta.env.VITE_TWITTER_CLIENT_ID),
  TWITTER_AUTH_REDIRECT_URI: String(import.meta.env.VITE_TWITTER_AUTH_REDIRECT_URI),
  GOOGLE_ANALYTICS_MEASUREMENT_ID: String(import.meta.env.VITE_GOOGLE_ANALYTICS_MEASUREMENT_ID),
}
